itkufs/billing/urls.py
from django.conf.urls import url

from itkufs.billing.views import (
    bill_create_transaction,
    bill_delete,
    bill_details,
    bill_list,
    bill_new_edit,
    bill_pdf,
)

urlpatterns = [
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/new/$", bill_new_edit, name="bill-new"
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/edit/$",
        bill_new_edit,
        name="bill-edit",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/transaction/$",
        bill_create_transaction,
        name="bill-create-transaction",
    ),
    url(r"^(?P<group>[0-9a-z_-]+)/billing/$", bill_list, name="bill-list"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/$",
        bill_details,
        name="bill-details",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/pdf/$",
        bill_pdf,
        name="bill-pdf",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/delete/$",
        bill_delete,
        name="bill-delete",
    ),
]

itkufs/common/urls.py
from django.conf.urls import url

from itkufs.common.views import login_user, switch_group
from itkufs.common.views.display import (
    account_summary,
    group_summary,
    group_balance_graph,
    export_transactions,
)
from itkufs.common.views.edit import (
    activate_account,
    assign_role_accounts,
    edit_group,
    new_edit_account,
)

urlpatterns = [
    # --- Index and login
    url(r"^$", login_user, name="index"),
    url(r"login/$", login_user, name="login"),
    url(r"^switch-group/$", switch_group, name="switch-group"),
    # --- Groups
    url(r"^(?P<group>[0-9a-z_-]+)/$", group_summary, name="group-summary"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/export$",
        export_transactions,
        name="export-transactions",
    ),
    url(r"^(?P<group>[0-9a-z_-]+)/edit/$", edit_group, name="edit-group"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/assign-role-accounts/$",
        assign_role_accounts,
        name="assign-role-accounts",
    ),
    # --- Accounts
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/$",
        account_summary,
        name="account-summary",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/new-account/$",
        new_edit_account,
        name="new-account",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/edit/$",
        new_edit_account,
        name="edit-account",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/activate/$",
        activate_account,
        name="activate-account",
    ),
    # --- Graphs
    url(
        r"^(?P<group>[0-9a-z_-]+)/graphs/group-balance/$",
        group_balance_graph,
        name="group-balance-graph",
    ),
]

itkufs/reports/urls.py
from django.conf.urls import url

from itkufs.reports.views import (
    balance,
    delete_list,
    income,
    new_edit_list,
    transaction_from_list,
    view_list,
    view_list_preview,
)

urlpatterns = [
    # --- Lists
    url(r"^(?P<group>[0-9a-z_-]+)/list/new/$", new_edit_list, name="new-list"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/$",
        view_list,
        name="view-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/preview/$",
        view_list_preview,
        name="view-list-preview",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/edit/$",
        new_edit_list,
        name="edit-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/delete/$",
        delete_list,
        name="delete-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/transaction/$",
        transaction_from_list,
        name="transaction-from-list",
    ),
    # --- Statements
    url(r"^(?P<group>[0-9a-z_-]+)/balance/$", balance, name="balance"),
    url(r"^(?P<group>[0-9a-z_-]+)/income/$", income, name="income"),
]

itkufs/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from itkufs import admin  # noqa: To register admin classes
from itkufs.reports.views import public_lists, view_public_list

if "itkufs.accounting" in settings.INSTALLED_APPS:
    import itkufs.accounting.admin  # noqa: To register admin classes

if "itkufs.reports" in settings.INSTALLED_APPS:
    import itkufs.reports.admin  # noqa: To register admin classes

urlpatterns = [
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", admin.site.urls),
    # View for magic i18n translation of js
    url(
        r"^i18n/js/$",
        JavaScriptCatalog.as_view(packages=['itkufs']),
        name="jsi18n",
    ),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    # Pull in lists before so that nothing else manages to catch the url
    url(r"^lists/$", public_lists, name="public-lists"),
    url(
        r"^lists/(?P<group>[0-9a-z_-]+)/(?P<list>[0-9a-z_-]+)/$",
        view_public_list,
        name="view-public-list",
    ),
    url(r"^", include("itkufs.common.urls")),
    url(r"^", include("itkufs.accounting.urls")),
    url(r"^", include("itkufs.billing.urls")),
    url(r"^", include("itkufs.reports.urls")),
    # Only reached using test server, but always used
    # for reverse lookup of URLs from views and templates
    url(
        r"^media/(?P<path>.*)$",
        serve,
        {"document_root": settings.MEDIA_ROOT},
        name="media",
    ),
]

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns = [
            url(r"^__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

itkufs/billing/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from itkufs.accounting.models import Group, Transaction


class Bill(models.Model):
    created = models.DateTimeField(_("created"), auto_now_add=True)
    description = models.TextField(_("description"))

    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    transaction = models.ForeignKey(
        Transaction, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return "{} - {}".format(self.created, self.description[:30])

    def is_editable(self):
        return self.transaction_id is None

    @property
    def status(self):
        if self.is_editable():
            return _("Pending")
        else:
            return _("Committed")

    def css_class(self):
        if self.is_editable():
            return "pending"
        else:
            return "committed"


class BillingLine(models.Model):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)

    description = models.CharField(_("description"), max_length=100)
    amount = models.DecimalField(
        _("amount"), max_digits=10, decimal_places=2, default=0
    )

    def __str__(self):
        return f"{self.description} - {self.amount}"

itkufs/accounting/views.py
from datetime import date, datetime
import os
from urlparse import urlparse

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.xheaders import populate_xheaders
from django.db.models import Q
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.newforms import form_for_instance, form_for_model
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _, ungettext
from django.views.generic.list_detail import object_list, object_detail
from django.db import transaction as db_transaction

from itkufs.common.decorators import limit_to_group, limit_to_owner, limit_to_admin
from itkufs.accounting.models import *
from itkufs.accounting.forms import *

@login_required
@limit_to_admin
def settlement_list(request, group, page='1', is_admin=False):
    """Show paginated list of settlements"""

    pass # TODO: Implement using object_list

@login_required
@limit_to_admin
def settlement_details(request, group, settlement, is_admin=False):
    """Show settlement summary"""

    pass # TODO: At least show all transactions related to a settlement

@login_required
@limit_to_admin
def new_edit_settlement(request, group, is_admin=False):
    """Create new and edit existing settlements"""

    # TODO: Implement support for editing settlements

    if request.method == 'POST':
        form = SettlementForm(request.POST)

        if form.is_valid():
            settlement = form.save(commit=False)

            settlement.group = group
            settlement.save()

            return HttpResponseRedirect(
                reverse('group-summary', args=(group.slug,)))
    else:
        form = SettlementForm()

    return render_to_response('accounting/settlement_form.html',
        {
            'is_admin': is_admin,
            'group': group,
            'form': form,
        },
        context_instance=RequestContext(request))

@login_required
@limit_to_group
def transaction_list(request, group, account=None, page='1',
    is_admin=False, is_owner=False):
    """Lists a group or an account's transactions"""

    if account and not is_owner and not is_admin:
        # FIXME: Incorporate into decorator. Jodal has an idea on this one.
        return HttpResponseForbidden(
            _('Forbidden if not account owner or group admin.'))

    # Get transactions
    transactions = (account or group).transaction_set_with_rejected

    # Pass on to generic view
    response = object_list(request, transactions,
        paginate_by=20,
        page=page,
        allow_empty=True,
        template_name='accounting/transaction_list.html',
        extra_context={
            'is_admin': is_admin,
            'is_owner': is_owner,
            'group': group,
            'account': account,
        },
        template_object_name='transaction')
    populate_xheaders(request, response, Group, group.id)
    return response

@login_required
def transaction_details(request, group, transaction, is_admin=False):
    """Shows all details about a transaction"""

    # Check that user is party of transaction or admin of group
    # FIXME: Do this with a decorator. Jodal has an idea on this one.
    if not is_admin and TransactionEntry.objects.filter(
        transaction__id=transaction,
        account__owner__id=request.user.id).count() == 0:
        return HttpResponseForbidden(_('The transaction may only be'
            ' viewed by group admins or a party of the transaction.'))

    # Pass on to generic view
    response = object_detail(request,
        Transaction.objects.all(),
        transaction,
        template_name='accounting/transaction_details.html',
        extra_context={
            'is_admin': is_admin,
            'group': group,
        },
        template_object_name='transaction')
    populate_xheaders(request, response, Transaction, transaction)
    return response

@login_required
@limit_to_owner
@db_transaction.commit_on_success
def transfer(request, group, account=None, transfer_type=None,
    is_admin=False, is_owner=False):
    """Deposit, withdraw or transfer money"""

    if request.method == 'POST':
        data = request.POST
    else:
        data = None

    if transfer_type == 'transfer':
        title = _('Transfer from account')
        form = TransferForm(data, account=account)
    elif transfer_type == 'deposit':
        title = _('Deposit to account')
        form = DepositWithdrawForm(data)
    elif transfer_type == 'withdraw':
        title = _('Withdrawal from account')
        form = DepositWithdrawForm(data)
    else:
        return HttpResponseForbidden(_('Forbidden if not group admin.'))

    if request.method == 'POST' and form.is_valid():
        amount = form.cleaned_data['amount']
        details = form.cleaned_data['details'].strip()

        if details == '':
            details = None

        transaction = Transaction(group=group)
        # FIXME: save() shouldn't be need if we figure out a reasonable hack
        transaction.save()

        if transfer_type == 'deposit':
            # Deposit to user account

            transaction.entry_set.add(
                TransactionEntry(account=account, credit=amount))
            transaction.entry_set.add(
                TransactionEntry(account=group.bank_account, debit=amount))

            transaction.set_registered(user=request.user, message=details)
            transaction.set_payed(user=request.user)

        elif transfer_type == 'withdraw':
            # Withdraw from user account

            transaction.entry_set.add(
                TransactionEntry(account=account, debit=amount))
            transaction.entry_set.add(
                TransactionEntry(account=group.bank_account, credit=amount))

            transaction.set_registered(user=request.user, message=details)

        elif transfer_type == 'transfer':
            # Transfer from user account to other user account

            credit_account = Account.objects.get(
                id=form.cleaned_data['credit_account'])

            transaction.entry_set.add(
                TransactionEntry(account=account, debit=amount))
            transaction.entry_set.add(
                TransactionEntry(account=credit_account, credit=amount))

            transaction.set_registered(user=request.user, message=details)

            if amount <= account.user_balance():
                transaction.set_payed(user=request.user)
                transaction.set_received(user=request.user)

        else:
            return HttpResponseForbidden(_('Forbidden if not group admin.'))

        request.user.message_set.create(
            message='Added transaction: %s' % transaction)

        return HttpResponseRedirect(reverse('account-summary',
            args=[account.group.slug, account.slug]))

    return render_to_response('accounting/transfer.html',
        {
            'is_admin': is_admin,
            'is_owner': is_owner,
            'account': account,
            'type': transfer_type,
            'title': title,
            'form': form,
            'group': group,
        },
        context_instance=RequestContext(request))

@login_required
@limit_to_admin
def approve_transactions(request, group, page='1', is_admin=False):
    """Approve transactions from members and other groups"""

    transactions = []
    to_be_rejected = []

    for t in group.not_received_transaction_set:
        choices = t.get_valid_logtype_choices()
        choices.insert(0, ('',''))

        if request.method == 'POST':
            form = ChangeTransactionForm(request.POST,
                prefix="transaction%d" % t.id, choices=choices, label=False)

            if form.is_valid():
                change_to = form.cleaned_data['change_to']

                if change_to == 'Reg':
                    t.set_registered(user=request.user)
                elif change_to == 'Pay':
                    t.set_payed(user=request.user)
                elif change_to == 'Rec':
                    t.set_received(user=request.user)
                elif change_to == 'Rej':
                    to_be_rejected.append((t))

                if change_to != 'Rej' and change_to != 'Rec':
                    tmp = t.get_valid_logtype_choices()
                    tmp.insert(0,('',''))
                    transactions.append((t,
                        ChangeTransactionForm(prefix='transaction%d' % t.id,
                            choices=tmp, label=False)))
            else:
                transactions.append((t,form))

        else:
            form = ChangeTransactionForm(choices=choices,
                prefix="transaction%d" % t.id, label=False)
            transactions.append((t,form))

    if to_be_rejected:
        form = RejectTransactionForm()
        return render_to_response('accounting/reject_transactions.html',
            {
                'is_admin': is_admin,
                'group': group,
                'transactions': to_be_rejected,
                'form': form,
            },
            context_instance=RequestContext(request))

    return render_to_response('accounting/approve_transactions.html',
        {
            'is_admin': is_admin,
            'group': group,
            'approve': True,
            'transaction_list': transactions,
        },
        context_instance=RequestContext(request))

@login_required
@limit_to_admin
def reject_transactions(request, group, is_admin=False):
    """Reject transactions from members and other groups"""

    if request.method != 'POST':
        return HttpResponseRedirect(
            reverse('group-summary', args=(group.slug,)))

    form = RejectTransactionForm(request.POST)
    to_be_rejected = request.POST.getlist('transactions')
    to_be_rejected = Transaction.objects.filter(id__in=to_be_rejected,

itkufs/templates/billing/base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ group.name }} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    &raquo; {% trans "Billing" %}
    {% if group %}
    &raquo; <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
    {% endif %}
{% endblock %}

{% block header %}&laquo;{{ group.name }}&raquo;{% endblock %}

{% block submenu %}

<h3>{% trans "Billing" %}</h3>

<ul class="menulist">
    <li class="admin"><a href="{% url "bill-new" group.slug %}">
        {% trans "New bill" %}</a></li>
    <li class="admin"><a href="{% url "bill-list" group.slug %}">
        {% trans "View bills" %}</a></li>
    <li><a href="{{ group.get_absolute_url }}">
        {% trans "Back to group" %}</a></li>
    {# <li>FIXME: We could do more with this list.</li> #}
</ul>

{% endblock %}

itkufs/templates/billing/bill_create_transaction.html
{% extends "billing/base.html" %}
{% load i18n %}

{% block header %}
    {% trans "Pay bill" %} #{{ bill.pk }}
{% endblock %}

{% block content %}

<form action="." method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">{% trans "Create transaction" %}</button>
</form>

{% endblock %}

itkufs/templates/billing/bill_delete.html
{% extends "billing/base.html" %}
{% load i18n %}

{% block header %}
    {% trans "Delete bill" %} #{{ bill.pk }}?
{% endblock %}

{% block content %}
  <form method="post" action=".">
    {% csrf_token %}

    <table class="tabledetails">
      <tr>
        <th>{% trans "Created" %}</th>
        <td style="width: 15em">{{ bill.created|date }} {{ bill.created|time }}</td>
      </tr>
      <tr>
        <th>{% trans "Transaction" %}</th>
        <td>
          {% if bill.transaction_id %}
            <a href="{% url "transaction-details" group.slug bill.transaction_id %}">
              {% trans "Transaction" %} #{{ bill.transaction_id }}
            </a>
          {% else %}
            &nbsp;&ndash;
          {% endif %}
        </td>
      </tr>
      <tr>
        <th>{% trans "Status" %}</th>
        <td class="{{ bill.css_class }}">{{ bill.status }}</td>
      </tr>
      <tr>
        <th>{% trans "Description" %}</th>
        <td>{{ bill.description|linebreaksbr }}</td>
      </tr>
    </table>

    <p>
      <button type="submit">{% trans "Delete" %}</button>
    </p>
  </form>
{% endblock %}

itkufs/templates/billing/bill_details.html
{% extends "billing/base.html" %}
{% load i18n %}
{% load ufs %}

{% block header %}
    {% trans "Bill" %} #{{ bill.pk }}
{% endblock %}

{% block content %}

<table class="tabledetails float_left">
  <tr>
    <th style="width: 5em">{% trans "Created" %}</th>
    <td style="width: 15em">{{ bill.created|date }} {{ bill.created|time }}</td>
  </tr>
  <tr>
    <th>{% trans "Transaction" %}</th>
    <td>
      {% if bill.transaction_id %}
        <a href="{% url "transaction-details" group.slug bill.transaction_id %}">
          {% trans "Transaction" %} #{{ bill.transaction_id }}
        </a>
      {% else %}
        &nbsp;&ndash;
      {% endif %}
    </td>
  </tr>
  <tr>
    <th>{% trans "Status" %}</th>
    <td class="{{ bill.css_class }}">{{ bill.status }}</td>
  </tr>
  <tr>
    <th>{% trans "Description" %}</th>
    <td>{{ bill.description|truncatewords:200|linebreaksbr }}</td>
  </tr>
  <tr>
    <th>{% trans "Action" %}</th>
    <td>
      <ul>
        <li class="admin">
          <a href="{% url "bill-pdf" group.slug bill.id %}">{% trans "Download PDF" %}</a>
        </li>
        {% if bill.is_editable %}
          <li class="admin">
            <a href="{% url "bill-edit" group.slug bill.id %}">{% trans "Edit bill" %}</a>
          </li>
          <li class="admin">
            <a href="{% url "bill-create-transaction" group.slug bill.id %}">{% trans "Create transaction" %}</a>
          </li>
        {% endif %}
        <li class="admin">
          <a href="{% url "bill-delete" group.slug bill.id %}">{% trans "Delete bill" %}</a>
        </li>
      </ul>
    </td>
  </tr>
</table>

<table class="tablelist float_left">
    <tr>
        <th style="width: 12em">{% trans "Description" %}</th>
        <th style="width: 4em">{% trans "Amount" %}</th>
    </tr>
    {% for line in bill.billingline_set.all %}
        <tr class="{% cycle "evenrow" "oddrow" %}">
            <td>{{ line.description }}</td>
            <td align="right">{{ line.amount|creditformat }}</td>
        </tr>
    {% endfor %}
</table>


{% endblock %}

itkufs/templates/billing/bill_form.html
{% extends "billing/base.html" %}
{% load i18n %}

{% block content %}

<form method="post" action=".">
{% csrf_token %}
{{ form.as_p }}

{{ formset.management_form }}

<label>{% trans "Billing lines" %}:</label>
<table class="tablelist">
    <tr>
        <th>{% trans "Description" %}</th>
        <th>{% trans "Amount" %}</th>
    </tr>
    {% for c in formset.forms %}
        <tr class="{% cycle "evenrow" "oddrow" %}">
            <td{% if c.description.errors %} class="error"{% endif %}>{{ c.description }}{{ c.id }}</td>
            <td{% if c.amount.errors %} class="error"{% endif %}>{{ c.amount }}</td>
        </tr>
    {% endfor %}
</table>

<p>
    <button type="submit">{% trans "Save bill" %}</button>
</p>

</form>

{% endblock %}

itkufs/templates/billing/bill_list.html
{% extends "billing/base.html" %}
{% load i18n %}

{% block header %}
    {{ block.super }} {% trans "Bills" %}
{% endblock %}

{% block content %}

<table class="tablelist">
    <tr>
        <th>{% trans "Ref." %}</th>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Description" %}</th>
        <th>{% trans "Status" %}</th>
    <tr>
    {% if not bills %}
        <tr>
            <td colspan="5">
                {% trans "No bills found." %}
            </td>
        <tr>
    {% endif %}
    {% for bill in bills %}
        <tr class="{% cycle "evenrow" "oddrow" %}">
            <td>
                <a href="{% url "bill-details" group.slug bill.id %}">
                    #{{ bill.id }}
                </a>
            </td>
            <td>
                {{ bill.created|date }}
                {{ bill.created|time }}
            </td>
            <td>
                {{ bill.description|truncatewords:5 }}
            </td>
            <td class="{{ bill.css_class }}">
                {{ bill.status }}
            </td>
        </tr>
    {% endfor %}
</table>

{% endblock %}