itkufs/billing/urls.py
from django.conf.urls import url

from itkufs.billing.views import (
    bill_create_transaction,
    bill_delete,
    bill_details,
    bill_list,
    bill_new_edit,
    bill_pdf,
)

urlpatterns = [
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/new/$", bill_new_edit, name="bill-new"
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/edit/$",
        bill_new_edit,
        name="bill-edit",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/transaction/$",
        bill_create_transaction,
        name="bill-create-transaction",
    ),
    url(r"^(?P<group>[0-9a-z_-]+)/billing/$", bill_list, name="bill-list"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/$",
        bill_details,
        name="bill-details",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/pdf/$",
        bill_pdf,
        name="bill-pdf",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/billing/(?P<bill>\d+)/delete/$",
        bill_delete,
        name="bill-delete",
    ),
]

itkufs/common/urls.py
from django.conf.urls import url

from itkufs.common.views import login_user, switch_group
from itkufs.common.views.display import (
    account_summary,
    group_summary,
    group_balance_graph,
    export_transactions,
)
from itkufs.common.views.edit import (
    activate_account,
    assign_role_accounts,
    edit_group,
    new_edit_account,
)

urlpatterns = [
    # --- Index and login
    url(r"^$", login_user, name="index"),
    url(r"login/$", login_user, name="login"),
    url(r"^switch-group/$", switch_group, name="switch-group"),
    # --- Groups
    url(r"^(?P<group>[0-9a-z_-]+)/$", group_summary, name="group-summary"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/export$",
        export_transactions,
        name="export-transactions",
    ),
    url(r"^(?P<group>[0-9a-z_-]+)/edit/$", edit_group, name="edit-group"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/assign-role-accounts/$",
        assign_role_accounts,
        name="assign-role-accounts",
    ),
    # --- Accounts
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/$",
        account_summary,
        name="account-summary",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/new-account/$",
        new_edit_account,
        name="new-account",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/edit/$",
        new_edit_account,
        name="edit-account",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/account/(?P<account>[0-9a-z_-]+)/activate/$",
        activate_account,
        name="activate-account",
    ),
    # --- Graphs
    url(
        r"^(?P<group>[0-9a-z_-]+)/graphs/group-balance/$",
        group_balance_graph,
        name="group-balance-graph",
    ),
]

itkufs/reports/urls.py
from django.conf.urls import url

from itkufs.reports.views import (
    balance,
    delete_list,
    income,
    new_edit_list,
    transaction_from_list,
    view_list,
    view_list_preview,
)

urlpatterns = [
    # --- Lists
    url(r"^(?P<group>[0-9a-z_-]+)/list/new/$", new_edit_list, name="new-list"),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/$",
        view_list,
        name="view-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/preview/$",
        view_list_preview,
        name="view-list-preview",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/edit/$",
        new_edit_list,
        name="edit-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/delete/$",
        delete_list,
        name="delete-list",
    ),
    url(
        r"^(?P<group>[0-9a-z_-]+)/list/(?P<list>[0-9a-z_-]+)/transaction/$",
        transaction_from_list,
        name="transaction-from-list",
    ),
    # --- Statements
    url(r"^(?P<group>[0-9a-z_-]+)/balance/$", balance, name="balance"),
    url(r"^(?P<group>[0-9a-z_-]+)/income/$", income, name="income"),
]

itkufs/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from itkufs import admin  # noqa: To register admin classes
from itkufs.reports.views import public_lists, view_public_list

if "itkufs.accounting" in settings.INSTALLED_APPS:
    import itkufs.accounting.admin  # noqa: To register admin classes

if "itkufs.reports" in settings.INSTALLED_APPS:
    import itkufs.reports.admin  # noqa: To register admin classes

urlpatterns = [
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", admin.site.urls),
    # View for magic i18n translation of js
    url(
        r"^i18n/js/$",
        JavaScriptCatalog.as_view(packages=['itkufs']),
        name="jsi18n",
    ),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    # Pull in lists before so that nothing else manages to catch the url
    url(r"^lists/$", public_lists, name="public-lists"),
    url(
        r"^lists/(?P<group>[0-9a-z_-]+)/(?P<list>[0-9a-z_-]+)/$",
        view_public_list,
        name="view-public-list",
    ),
    url(r"^", include("itkufs.common.urls")),
    url(r"^", include("itkufs.accounting.urls")),
    url(r"^", include("itkufs.billing.urls")),
    url(r"^", include("itkufs.reports.urls")),
    # Only reached using test server, but always used
    # for reverse lookup of URLs from views and templates
    url(
        r"^media/(?P<path>.*)$",
        serve,
        {"document_root": settings.MEDIA_ROOT},
        name="media",
    ),
]

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns = [
            url(r"^__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

itkufs/accounting/models.py
import datetime

from django.conf import settings
from django.core.mail import send_mail
from django.db import connection, models, transaction as db_transaction
from django.db.models import (
    Q,
    Sum,
    When,
    Case,
    Value,
    F,
    ExpressionWrapper,
    IntegerField,
)
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.encoding import smart_text
from django.utils.translation import ugettext_lazy as _, ugettext

from typing import List as ListType


class Group(models.Model):
    name = models.CharField(_("name"), max_length=100)
    slug = models.SlugField(
        _("slug"), unique=True, help_text=_("A shortname used in URLs.")
    )
    admins = models.ManyToManyField(User, verbose_name=_("admins"), blank=True)
    warn_limit = models.IntegerField(
        _("warn limit"),
        null=True,
        blank=True,
        help_text=_(
            "Warn user of low balance at this limit, "
            "leave blank for no limit."
        ),
    )
    block_limit = models.IntegerField(
        _("block limit"),
        null=True,
        blank=True,
        help_text=_("Limit for blacklisting user, leave blank for no limit."),
    )
    logo = models.ImageField(
        upload_to="logos",
        blank=True,
        help_text=_("A small image that will be added to lists."),
    )

    email = models.EmailField(
        blank=True, help_text=_("Contact address for group.")
    )

    account_number = models.CharField(
        blank=True, max_length=11, help_text=_("Bank account for group.")
    )

    class Meta:
        ordering = ("name",)
        verbose_name = _("group")
        verbose_name_plural = _("groups")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("group-summary", kwargs={"group": self.slug})

    def get_account_number_display(self):
        n = self.account_number
        return ".".join([n[:4], n[4:6], n[6:]])

    def save(self, *args, **kwargs):
        if not len(self.slug):
            raise ValueError("Slug cannot be empty.")
        super().save(*args, **kwargs)

        # Create default accounts
        if not self.account_set.count():
            # TODO change this into a magic loop?
            bank = Account(
                name=ugettext("Bank"),
                slug="bank",
                group_account=True,
                type=Account.ASSET_ACCOUNT,
                group=self,
            )
            bank.save()
            bank_role = RoleAccount(
                group=self, role=RoleAccount.BANK_ACCOUNT, account=bank
            )
            bank_role.save()

            cash = Account(
                name=ugettext("Cash"),
                slug="cash",
                group_account=True,
                type=Account.ASSET_ACCOUNT,
                group=self,
            )
            cash.save()
            cash_role = RoleAccount(
                group=self, role=RoleAccount.CASH_ACCOUNT, account=cash
            )
            cash_role.save()

    def get_user_account_set(self) -> ListType["Account"]:
        """Returns all user accounts belonging to group"""
        return self.account_set.exclude(group_account=True)

    user_account_set = property(get_user_account_set, None, None)

    def get_group_account_set(self) -> ListType["Account"]:
        """Returns all non-user accounts belonging to group"""
        return self.account_set.filter(group_account=True)

    group_account_set = property(get_group_account_set, None, None)

    # --- Transaction set methods
    # Please keep in sync with Account's set methods

    def get_transaction_set_with_rejected(self) -> ListType["Transaction"]:
        """Returns all transactions connected to group, including rejected"""
        return self.real_transaction_set.exclude(
            state=Transaction.UNDEFINED_STATE
        ).distinct()

    transaction_set_with_rejected = property(
        get_transaction_set_with_rejected, None, None
    )

    def get_transaction_set(self) -> ListType["Transaction"]:
        """Returns all transactions connected to group, excluding rejected"""
        return self.transaction_set_with_rejected.exclude(
            state=Transaction.REJECTED_STATE
        )

    transaction_set = property(get_transaction_set, None, None)

    def get_pending_transaction_set(self) -> ListType["Transaction"]:
        """Returns all pending transactions connected to group"""
        return self.transaction_set.filter(state=Transaction.PENDING_STATE)

    pending_transaction_set = property(get_pending_transaction_set, None, None)

    def get_committed_transaction_set(self) -> ListType["Transaction"]:
        """Returns all committed transactions connected to group"""
        return self.transaction_set.filter(state=Transaction.COMMITTED_STATE)

    committed_transaction_set = property(
        get_committed_transaction_set, None, None
    )

    def get_rejected_transaction_set(self) -> ListType["Transaction"]:
        """Returns all rejected transactions connected to group"""
        return self.transaction_set_with_rejected.filter(
            state=Transaction.REJECTED_STATE
        )

    rejected_transaction_set = property(
        get_rejected_transaction_set, None, None
    )

    def get_balance_history_set(self):
        """Returns historical balance data for this group"""
        raise NotImplementedError("Only supported for accounts, not groups")

    balance_history_set = property(get_balance_history_set, None, None)


CONFIRMED_BALANCE_SQL = """
SELECT sum(debit) - sum(credit)
    FROM accounting_transactionentry AS te
    JOIN accounting_transaction AS t ON (te.transaction_id = t.id)
WHERE account_id = %s AND t.state = 'Com'
"""

FUTURE_BALANCE_SQL = """
SELECT sum(debit) - sum(credit)
    FROM accounting_transactionentry AS te
    JOIN accounting_transaction AS t ON (te.transaction_id = t.id)
WHERE account_id = %s AND t.state != 'Rej'
"""

GROUP_BLOCK_LIMIT_SQL = """
SELECT accounting_group.block_limit
    FROM accounting_group
WHERE accounting_group.id = accounting_account.group_id
"""

# FIXME This query does not work on Sqlite
ACCOUNT_BALANCE_HISTORY_SQL = """
SELECT
    account.id,
    short_name AS user,
    extract(epoch from last_modified)*1000 as date,
    sum(credit)-sum(debit) AS saldo
FROM accounting_account account
    JOIN accounting_transactionentry AS entry ON account.id = entry.account_id
    JOIN accounting_transaction trans ON entry.transaction_id = trans.id
WHERE account.id = %s AND state='Com'
GROUP BY account.id, short_name, last_modified
ORDER BY date
"""

ACCOUNT_TOTAL_USED = """
SELECT sum(debit)
FROM accounting_transactionentry AS te
JOIN accounting_transaction AS t ON (te.transaction_id = t.id)
WHERE account_id = %s AND t.state = 'Com'
"""


class AccountManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .extra(
                select={
                    "confirmed_balance_sql": (
                        CONFIRMED_BALANCE_SQL % "accounting_account.id"
                    ),
                    "future_balance_sql": FUTURE_BALANCE_SQL
                    % "accounting_account.id",
                    "group_block_limit_sql": GROUP_BLOCK_LIMIT_SQL,
                }
            )
        )


class HistoricalAccountManager(models.Manager):
    def with_balance_change(self, from_date: str, to_date: str):
        """
        Returns a queryset of accounts with their change in normalized balance
        between the given dates.

        A normalized balance means that equity, liability, and income accounts
        will have a positive balance if their credit amount is greater than
        their debit amount, and vice versa for expense and asset accounts.
        """
        # Find entries from committed transactions in the period
        filters = (
            Q(transactionentry__transaction__state=Transaction.COMMITTED_STATE)
            & Q(transactionentry__transaction__date__gte=from_date)
            & Q(transactionentry__transaction__date__lte=to_date)
        )

        # Get changes in balance for accounts with transactions in the period
        return self.filter(filters).annotate(
            sum_debit=Sum("transactionentry__debit"),
            sum_credit=Sum("transactionentry__credit"),
            difference=ExpressionWrapper(
                F("sum_debit") - F("sum_credit"),
                output_field=models.DecimalField(),
            ),
            normal_balance=Case(
                When(difference__isnull=True, then=Value(0)),
                When(
                    type__in=[
                        Account.ASSET_ACCOUNT,
                        Account.EXPENSE_ACCOUNT,
                    ],
                    then="difference",
                ),
                default=F("difference") * -1,
                output_field=models.DecimalField(),
            ),
        )


class Account(models.Model):
    ASSET_ACCOUNT = "As"  # Eiendeler/aktiva
    LIABILITY_ACCOUNT = "Li"  # Gjeld/passiva
    EQUITY_ACCOUNT = "Eq"  # Egenkapital
    INCOME_ACCOUNT = "In"  # Inntekt
    EXPENSE_ACCOUNT = "Ex"  # Utgift
    ACCOUNT_TYPE = (
        (ASSET_ACCOUNT, _("Asset")),
        (LIABILITY_ACCOUNT, _("Liability")),
        (EQUITY_ACCOUNT, _("Equity")),
        (INCOME_ACCOUNT, _("Income")),
        (EXPENSE_ACCOUNT, _("Expense")),
    )

    objects = AccountManager()
    historical_objects = HistoricalAccountManager()

    name = models.CharField(_("name"), max_length=100)
    short_name = models.CharField(_("short name"), max_length=100, blank=True)
    slug = models.SlugField(
        _("slug"), help_text=_("A shortname used in URLs etc.")
    )
    group = models.ForeignKey(
        Group, on_delete=models.CASCADE, verbose_name=_("group")
    )
    type = models.CharField(
        _("type"), max_length=2, choices=ACCOUNT_TYPE, default=LIABILITY_ACCOUNT
    )

itkufs/common/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _, ungettext

from itkufs.accounting.models import Group, Account

def login_user(request):
    """Login user"""

    if not request.user.is_authenticated():
        user = authenticate(request=request)
        if user is not None:
            login(request, user)
        else:
            return HttpResponseForbidden(_('Login failed'))

    try:
        # Redirect to one of the user's accounts
        account = request.user.account_set.all()[0]
        url = reverse('account-summary',
                      kwargs={'group': account.group.slug,
                              'account': account.slug})
        return HttpResponseRedirect(url)
    except IndexError:
        pass

    # Tell the user he has a user, but not an account
    return render_to_response('common/no_account.html',
                              context_instance=RequestContext(request))

@login_required
def account_switch(request, is_admin=False):
    """Switch to account summary for the selected account"""

    if request.method != 'POST':
        raise Http404
    group_slug = request.POST['group']
    account = get_object_or_404(Account, owner=request.user,
        group__slug=group_slug)
    return HttpResponseRedirect(reverse('account-summary',
        kwargs={
            'group': account.group.slug,
            'account': account.slug,
        }))

@login_required
def static_page(request, template, is_admin=False):
    return render_to_response(template,
                              {
                                  'is_admin': is_admin,
                              },
                              context_instance=RequestContext(request))

itkufs/templates/accounting/base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% if account %}
        {{ account.name }} -
    {% endif %}
    {{ group.name }} - {{ block.super }}
{% endblock %}


{% block breadcrumbs %}
    {{ block.super }} &raquo; {% trans "Accounting" %} &raquo;
    {% if account %}
        <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
        &raquo;
        <a href="{{ account.get_absolute_url }}">{{ account.name }}</a>
    {% else %}
        <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
    {% endif %}
{% endblock %}


{% block header %}
    {% if account %}
        &laquo;{{ account.name }}&raquo;
    {% else %}
        &laquo;{{ group.name }}&raquo;
    {% endif %}
{% endblock %}


{% block submenu %}
    <h3>&laquo;{{ group.name }}&raquo;</h3>

    <ul class="menulist">
        <li><a href="{{ group.get_absolute_url }}">
            {% trans "Summary" %}</a></li>
        {% include "common/group_action.html" %}
    </ul>

    {% if account %}
        <h3>&laquo;{{ account.name }}&raquo;</h3>

        <ul class="menulist">
            <li><a href="{{ account.get_absolute_url }}">
                {% trans "Summary" %}</a></li>
            {% include "common/account_action.html" %}
        </ul>
    {% endif %}
{% endblock %}


{% block helptips %}

<h3>{% trans "Help" %}</h3>

<p>{% blocktrans %}<em>Balance</em> is always seen from the perspective of the
group. If the user account balance is positive, it is a liability to the group.
If the user account balance is negative, it is an asset and the
user owes money to the group.{% endblocktrans %}</p>

{% endblock %}

itkufs/templates/accounting/group_summary.html
{% extends "accounting/base.html" %}
{% load i18n %}

{% block helptips %}

<h3>{% trans  "Help" %}</h3>

<p>{% blocktrans %}In all group views <em>balance</em> is seen from the
perspective of the group. If the group owes people money, it is a liability,
and their user account balance is negative. If people owes the group money, it
is an asset, and their user account balance is positive."{% endblocktrans %}</p>

{% endblock %}


{% block content %}

<div id="groupinfo">
<h3>{% trans "Group info" %}</h3>
<table class="tabledetails">
    <tr>
        <th>{% trans "Name" %}</th>
        <td>{{ group.name }}</td>
    </tr>

    <tr>
        <th>{% trans "Warning limit" %}</th>
        {% if group.warn_limit %}
            <td>{{ group.warn_limit|stringformat:"0.2f" }}</td>
        {% else %}
            <td>{{ group.warn_limit|default_if_none:_("None") }}</td>
        {% endif %}
    </tr>

    <tr>
        <th>{% trans "Blocking limit" %}</th>
        {% if group.warn_limit %}
            <td>{{ group.block_limit|stringformat:"0.2f" }}</td>
        {% else %}
            <td>{{ group.block_limit|default_if_none:_("None") }}</td>
        {% endif %}
    </tr>
</table>
</div>

{% if is_admin %}
<div id="actions">
<h3>{% trans "Actions" %}</h3>
<ul>
{% include "accounting/group_action.html" %}
{% if is_admin %}
<li class="admin"><a href="{% url edit-group group.slug%}">
    {% trans "Edit group" %}</a></li>
<li class="admin"><a href="{% url new-account group.slug %}">
     {% trans "New account" %}</a></li>
<li class="admin"><a href="{% url new-list group.slug %}">
     {% trans "New list" %}</a></li>
{% endif %}
</ul>
</div>
{% endif %}

<div id="statements">
<h3>{% trans "Statements" %}</h3>
<ul>
    <li><a href="{% url balance group.slug %}">{% trans "Balance statement" %}</a></li>
    <li><a href="{% url income group.slug %}">{% trans "Income statement" %}</a></li>
</ul>
</div>

<div id="lists">
<h3>{% trans "Lists" %}</h3>
<ul>
{% if group.list_set.count %}
    {% for list in group.list_set.all %}
    <li><a href="{% url view-list group.slug,list.slug %}">
        {{ list.name }}</a></li>
    {% endfor %}
{% else %}
    {% if is_admin %}
        <li class="admin"><a href="{% url new-list group.slug %}">
            {% trans "No lists found" %}</a></li>
    {% else %}
        <li>{% trans "No lists found" %}</li>
    {% endif %}
{% endif %}
</ul>
</div>

{% if is_admin or not group.admin_only %}

<div id="accounts">
{% if not group.account_set.count %}
<h3>{% trans "Accounts" %}</h3>
<p>{% trans "No accounts found." %}</p>
{% else %}

<h3>{% trans "Accounts" %}</h3>

<div class="float_left">
<table class="tablelist">
    <caption>{% trans "User accounts" %}</caption>
    <tr>
        <th>{% trans "Account" %}</th>
        <th>{% trans "Type" %}</th>
        <th>{% trans "Balance" %}</th>
    </tr>
{% for account in group.user_account_set %}
    {% if all or account.active %}
    <tr class="{% cycle evenrow,oddrow %}{% if not account.active %} inactive{% endif %}">
        {% if is_admin %}
        <td><a href="{% url account-summary group.slug,account.slug %}">{{ account.name }}</a></td>
        {% else %}
        <td>{{ account.name }}</td>
        {% endif %}
        <td>{{ account.get_type_display }}</td>
        <td class="align_right{% if account.is_blocked %} blocked{% endif %}">{{ account.balance|stringformat:"0.2f" }}</td>
    </tr>
    {% endif %}
{% endfor %}
</table>

</div>
<div class="float_left">
<table class="tablelist">
    <caption>{% trans "Group accounts" %}</caption>
    <tr>
        <th>{% trans "Account" %}</th>
        <th>{% trans "Type" %}</th>
        <th>{% trans "Balance" %}</th>
    </tr>
{% for account in group.group_account_set %}
    {% if all or account.active %}
    <tr class="{% cycle evenrow,oddrow %}{% if not account.active %} inactive{% endif %}">
        {% if is_admin %}
        <td><a href="{% url account-summary group.slug,account.slug %}">{{ account.name }}</a></td>
        {% else %}
        <td>{{ account.name }}</td>
        {% endif %}
        <td>{{ account.get_type_display }}</td>
        <td class="align_right{% if account.is_blocked %} blocked{% endif %}">{{ account.balance|stringformat:"0.2f" }}</td>
    </tr>
    {% endif %}
{% endfor %}
</table>
</div>

<p class="clear">
{% if all %}
    <a href=".">{% trans "Hide inactive accounts" %}</a>
{% else %}
    <a href="?all">{% trans "Show inactive accounts" %}</a>
{% endif %}
</p>

{% endif %}
</div>

{% endif %}

{% endblock %}

itkufs/templates/accounting/transaction_form.html
{% extends "accounting/base.html" %}
{% load i18n %}


{% block title %}
    {% if transaction.id %}
        {% trans "Edit transaction" %}
    {% else %}
        {% trans "New transaction" %}
    {% endif %}
    - {{ block.super }}
{% endblock %}


{% block breadcrumbs %}
    {{ block.super }}
    &raquo;
    <a href="{% url "new-transaction" group.slug %}">
        {% if transaction.id %}
            {% trans "Edit transaction" %}
        {% else %}
            {% trans "New transaction" %}
        {% endif %}
    </a>
{% endblock %}


{% block header %}
    {{ block.super }}
    &ndash; {% trans "New transaction" %}
{% endblock %}



{% block content %}

<form action="." method="post" id="newtransaction">
    {% csrf_token %}

    {% if errors %}
        <ul class="error">
            {% for e in errors %}
                <li>{{ e }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if transaction.log_set.all %}
    <p><label>Transactionlog:</label></p>
    <dl>
        {% for l in transaction.log_set.all %}
        <dt>{{ l.timestamp|date }} {{ l.timestamp|time }}</dt>
        <dd>
            <em>{{ l.user|default:_("Unknown") }}:</em>
            {{ l.message|default:_("No transaction log message") }}
        </dd>
        {% endfor %}
    </dl>
    {% endif %}

    {{ settlement_form.as_p }}

    <label>{% trans "Account:" %}</label>
    <table class="tablelist">
        <thead>
            <tr>
                <th colspan="2">{% trans "Account" %}</th>
                <th>{% trans "Type" %}</th>
                <th>{% trans "Balance" %}</th>
                <th>{% trans "Debit" %}</th>
                <th>{% trans "Credit" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for a,f in group_forms %}
            <tr class="{% cycle "evenrow" "oddrow" as rowcolors %}">
                <td{% if not a.short_name %} colspan="2"{% endif %}><a href="{% url "account-summary" group.slug a.slug %}">{{ a.name }}</a></td>
                {% if a.short_name %}
                <td>{{ a.short_name|default:"-" }}</td>
                {% endif %}
                <td class="{{a.type}}">{{ a.get_type_display }}</td>
                <td id="balance-{{ a.id }}" class="balance number">{{ a.normal_balance|floatformat:2 }}</td>
                <td{% if f.debit.errors %} class="error"{% endif %} id="{{ f.auto_id }}">{{ f.debit }}</td>
                <td{% if f.credit.errors %} class="error"{% endif %} id="{{ f.auto_id }}">{{ f.credit }}</td>
            </tr>
        {% endfor %}
        {% for a,f in user_forms %}
            <tr class="{% cycle rowcolors %}">
                <td{% if not a.short_name %} colspan="2"{% endif %}><a href="{% url "account-summary" group.slug a.slug %}">{{ a.name }}</a></td>
                {% if a.short_name %}
                <td>{{ a.short_name|default:"-" }}</td>
                {% endif %}
                <td class="{{ a.type }}">{{ a.get_type_display }}</td>
                <td id="balance-{{ a.id }}" class="balance number">{{ a.normal_balance|floatformat:2 }}</td>
                <td{% if f.debit.errors %} class="error"{% endif %} id="{{ f.auto_id }}">{{ f.debit }}</td>
                <td{% if f.credit.errors %} class="error"{% endif %} id="{{ f.auto_id }}">{{ f.credit }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p>
        <button type="submit">{% trans "Save transaction" %}</button>
    </p>
</form>

{% endblock %}